language: android
sudo: required
jdk: oraclejdk8

before_install:
 - chmod +x gradlew

android:
 components:
 - tools
 - platform-tools
 - build-tools 26.0.1
 - android 26
 - extra-google-m2repository
 - extra-android-m2repository
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+