language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-28

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo yes | sdkmanager "build-tools;28.0.3"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
 - chmod +x gradlew
 - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
 - export JAVA_HOME=$JAVA8_HOME

script:
 - cd $TRAVIS_BUILD_DIR/
 - chmod +x gradlew 
 - ./gradlew testDebugUnitTest assembleDebug 
 - chmod +x ./upload-gh-pages.sh
 - ./upload-gh-pages.sh
 
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
